language: d

# latest dmd, gdc and ldc
d:
  - dmd
  - gdc
  - ldc

install:
  # Install doveralls from the latest github release
  - wget -q -O - "http://bit.ly/Doveralls" | bash

script:
  - dub test --compiler=${DC} -b unittest-cov
  - ./doveralls
